# Generated by Django 4.0.3 on 2022-03-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutnotes', '0003_alter_exercise_repsss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='repsss',
            field=models.JSONField(blank=True, default={'1': 0}),
        ),
    ]
