# Generated by Django 4.0.3 on 2022-03-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutnotes', '0005_workout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='notes',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
